export const PLACEHOLDERS = {
  FORM_ENDPOINT: '{{FORM_ENDPOINT}}',
  RECIPIENT_LEGAL_NAME: '{{RECIPIENT_LEGAL_NAME}}',
  RECIPIENT_ADDRESS: '{{RECIPIENT_ADDRESS}}',
  RECIPIENT_KVKK_CONTACT_EMAIL: '{{RECIPIENT_KVKK_CONTACT_EMAIL}}',
  DATA_CONTROLLER_LEGAL_NAME: '{{DATA_CONTROLLER_LEGAL_NAME}}',
  DATA_CONTROLLER_VERBIS_NO: '{{DATA_CONTROLLER_VERBIS_NO}}',
  LEAD_PURPOSE_TR: '{{LEAD_PURPOSE_TR}}',
  RETENTION_PERIOD_TR: '{{RETENTION_PERIOD_TR}}',
  CONVERSION_API_ENDPOINT: '{{CONVERSION_API_ENDPOINT}}',
} as const;
